version: '2.4'
services:
  frontend:
    build: ../frontend
    container_name: greeting_frontend
    ports:
      - 3000:3000

  bff:
    build:
      context: ../
      dockerfile: ./graphql-server/Dockerfile
    container_name: greeting_bff
    ports:
      - 4000:4000

  api:
    image: wildmouse/greeting_api:latest
    container_name: greeting_api
    # TODO: remove depends on for more resiliency
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    container_name: greeting_mysql
    environment:
      MYSQL_ROOT_PASSWORD: greeting
      MYSQL_DATABASE: greeting
      MYSQL_USER: greeting_user
      MYSQL_PASSWORD: greeting
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping" ,"-h", "localhost", "-uroot", "-pgreeting"]
      timeout: 20s
      retries: 10
